# Generated by Django 5.2.17 on 2026-09-19 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='API Key')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_key', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': 'API 密钥',
                'verbose_name_plural': 'API 密钥',
                'db_table': 'api_key',
            },
        ),
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=16, unique=True, verbose_name='系统短码')),
                ('alias', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='自定义短码')),
                ('original_url', models.URLField(max_length=2048, verbose_name='原始长链接')),
                ('remarks', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='short_urls', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '短链接',
                'verbose_name_plural': '短链接',
                'db_table': 'short_url',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='访问 IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=512, verbose_name='User-Agent')),
                ('device_type', models.CharField(default='pc', max_length=16, verbose_name='设备类型')),
                ('browser', models.CharField(blank=True, default='', max_length=32, verbose_name='浏览器')),
                ('os_name', models.CharField(blank=True, default='', max_length=32, verbose_name='操作系统')),
                ('referer', models.URLField(blank=True, max_length=1024, null=True, verbose_name='来源页')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='访问时间')),
                ('short_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='shortener.shorturl', verbose_name='短链接')),
            ],
            options={
                'verbose_name': '访问记录',
                'verbose_name_plural': '访问记录',
                'db_table': 'access_log',
            },
        ),
        migrations.AddIndex(
            model_name='shorturl',
            index=models.Index(fields=['creator', 'created_at'], name='idx_creator_created'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['short_url', 'accessed_at'], name='idx_url_time'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['accessed_at'], name='idx_accessed_at'),
        ),
    ]
